### ISSUE TITLE
Plot not rendering correctly

### ISSUE THREAD

**Issue by dsoto** [danielfrg/pelican-ipynb#24] opened 2015-02-15 15:43 UTC
I'm encountering a strange condition where the embedded png of a plot seems to be truncated and mixed with what looks like CSS code in the rendered output.  Inspecting the html, it looks like the png has a bunch of CSS appended.  I haven't been able to create a simple example yet.

**Comment by danielfrg** [comment] 2015-02-16 16:21
What versions of ipython and pelican are you using?

**Comment by dsoto** [comment] 2015-02-17 02:37
~ > pelican --version
3.5.0
~ > ipython --version
2.3.1

**Comment by dsoto** [comment] 2015-02-17 02:45
You can see the post at
http://danielrsoto.com/blog/2015/02/01/debugging/

**Comment by danielfrg** [comment] 2015-03-25 20:24
I just updated the plugin to support new versions of ipython and pelican and that might have fixed this issue since I was able to render a plot without issues: http://danielfrg.com/drafts/ipython-notebook-test.html

**Comment by dsoto** [comment] 2015-03-26 04:18
I'm seeing this issue on my recent download of master.  
Here is a minimal example where the plot rendering seems to break and insert CSS around 120 plotting points.
http://danielrsoto.com/drafts/debugging-2.html

**Comment by danielfrg** [comment] 2015-03-26 05:06
I cannot reproduce the error :(

I just did the same plot on my test post () but it renders fine for me.

Are you in the latest pelical and ipython? This is my environment:

```
```

**Comment by dsoto** [comment] 2015-03-28 01:23
Thank you very much.  I matched all versions in a conda environment and now I'm able to plot without issues.  If I find myself with enough time, I may try to isolate the offending package.

**Comment by danielfrg** [comment] 2015-03-28 03:23
Good to know, let me know if you find out.

Closing now.

**Closed by danielfrg** 2015-03-28 03:23 UTC
